### ISSUE TITLE
Input code causing segmentation fault.

### ISSUE THREAD

**Issue by MovingtoMars** [andrewrk/zig#92] opened 2016-01-27 10:36 UTC
The compiler will have a segmentationf fault if it sees this code:
```
pub fn do() -> &void {
    const y = 5;
    &y
}
```

**Comment by andrewrk** [comment] 2016-01-27 17:38
This is supposed to be an error because y has no type and you're taking the address of it

**Comment by andrewrk** [comment] 2016-01-27 19:12
duplicate of #85 

will fix right now

**Closed by andrewrk** 2016-01-27 19:12 UTC
