### ISSUE TITLE
Forgetting to declare main as pub causes segmentation fault at runtime

### ISSUE THREAD

**Issue by AndreaOrru** [andrewrk/zig#319] opened 2017-04-13 09:25 UTC
```
fn main() -> %void {
}
```

```
andrea@soho:~$ zig build_exe test.zig
andrea@soho:~$ ./test
Segmentation fault
```

Should we at least print a warning?

**Comment by andrewrk** [comment] 2017-04-13 10:13
related: #30

**Comment by andrewrk** [comment] 2017-04-18 17:29
actually I believe this is a duplicate of #30

**Closed by andrewrk** 2017-04-18 17:29 UTC
Labels: bug
